jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # For dart
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      # for java
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      # for flutter
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '2.5.x'

      - name: Install dependencies
        run: flutter pub get.

      # Consider passing '--fatal-infos' for slightly stricter 
      # analysis.
      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and 
      # dependency on
      # package:test for this step to succeed. Note that Flutter 
      # projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test
